name: Créer un APK

on:
  push:
    branches: [ principal ]

jobs:
  build:
    name: Créer un APK avec Gradle
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configurer JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Donner la permission à gradlew
        run: chmod +x ./gradlew

      - name: Construire l’APK
        run: ./gradlew assembleDebug

      - name: Télécharger l’APK généré
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
